Configure check for WordNet corrected

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4341,8 +4341,8 @@ _ACEOF
 
 else
 
-{ { echo "$as_me:$LINENO: error: echo \"You must have wordnet development headers to build.\"; echo \"(http://wordnet.princeton.edu/obtain)\"" >&5
-echo "$as_me: error: echo \"You must have wordnet development headers to build.\"; echo \"(http://wordnet.princeton.edu/obtain)\"" >&2;}
+{ { echo "$as_me:$LINENO: error: You must have WordNet development headers (wordnet-dev) to build. (http://wordnet.princeton.edu/obtain). Refer INSTALL file for further details." >&5
+echo "$as_me: error: You must have WordNet development headers (wordnet-dev) to build. (http://wordnet.princeton.edu/obtain). Refer INSTALL file for further details." >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -6895,7 +6895,7 @@ Artha is now configured!
 
   Once installed, type \`artha\` to run.
 
-    See INSTALL file for further details.
+    Refer INSTALL file for further details.
 " >&5
 echo "${ECHO_T}
 Artha is now configured!
@@ -6909,6 +6909,6 @@ Artha is now configured!
 
   Once installed, type \`artha\` to run.
 
-    See INSTALL file for further details.
+    Refer INSTALL file for further details.
 " >&6; }
 
